package repository;

import java.util.*;
import java.io.*;

import entity.Manager;

public class ManagerRepository extends UserRepository<Manager> {
	/**
	 * 
	 */
	private static final long serialVersionUID = -4139573877991643327L; // auto-generated by Eclipse
	private static ManagerRepository instance;
	private List<Manager> managers;
	
	public ManagerRepository() {
		this.managers = new ArrayList<Manager>();
	}
	
	public static ManagerRepository getInstance() {
        if (instance == null) {
            instance = new ManagerRepository();
        }
        return instance;
	}
	
	private Object readResolve() throws ObjectStreamException {
	    return getInstance(); 
	}
	
	@Override
	public void importFromCSV() {
		String filePath = "csv\\ManagerList.csv";
		Scanner sc;
		try {
			sc = new Scanner(new FileReader(filePath));
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			System.out.println("ManagerList.csv file is not found. Please ensure that the file is inside csv folder. ");
			return;
		}
		
		sc.nextLine(); // skip the csv list heading
		while(sc.hasNext()) {
			Manager newManager = new Manager();
			String line = sc.nextLine();
			String[] parts = line.split(",");
			newManager.setName(parts[0]);
			newManager.setNRIC(parts[1]);
			newManager.setAge(Integer.parseInt(parts[2]));
			newManager.setMarried(parts[3].equals("Married")? true : false);
			newManager.setPassword(parts[4]);
			this.managers.add(newManager);	
		}	
		sc.close();
	}


	public List<Manager> getManagers() {
		return managers;
	}


	public void setManagers(List<Manager> managers) {
		this.managers = managers;
	}


	@Override
	public Manager searchByNRIC(String NRIC) {
		Manager result = null;
		for (Manager manager : managers) {
			if (manager.getNRIC().equals(NRIC)) result = manager;
			break;
		}
		
		return result;
	}
	
	@Override
	public Manager searchByName(String name) {
	    for (Manager manager : this.getManagers()) {
	        if (manager.getName().equalsIgnoreCase(name.trim())) {
	            return manager;
	        }
	    }
	    return null; 
	}
}
