package repository;

import java.util.*;

import entity.Manager;

public class ManagerRepository extends RepositoryWithCSV {
	/**
	 * 
	 */
	private static final long serialVersionUID = -4139573877991643327L; // auto-generated by Eclipse
	private List<Manager> managers;
	
	public ManagerRepository() {
		this.managers = new ArrayList<Manager>();
	}
	
	
	@Override
	public void importFromCSV() {
		;
	}


	public List<Manager> getManagers() {
		return managers;
	}


	public void setManagers(List<Manager> managers) {
		this.managers = managers;
	}
}
